# Generated by Django 5.0.3 on 2024-05-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gerenciador_de_tarefas_app', '0002_tarefa_inserted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='inserted_at',
        ),
    ]
