# Generated by Django 5.0.3 on 2024-05-20 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gerenciador_de_tarefas_app', '0004_tarefa_inserted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='inserted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 2, 28, 36, 694856, tzinfo=datetime.timezone.utc)),
        ),
    ]
