# Generated by Django 5.0.3 on 2024-05-23 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gerenciador_de_tarefas_app', '0005_alter_tarefa_inserted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
