# Generated by Django 5.0.3 on 2024-05-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gerenciador_de_tarefas_app', '0007_usuario_tarefa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
